###
# updates the APT package cache and install packages necessary for web
# servers
#
---

- name: ensure apt cache is up to date
  apt: update_cache=yes
  sudo: yes

- name: ensure that web packages are installed
  apt: name={{item}}
  sudo: yes
  with_items:
    - git
    - python-dev
    - libpq-dev
    - python-virtualenv
    - nginx
    - supervisor
    - postgresql-client-common
    - postgresql-client
